[package]
name = "knowledge-base-models"
description = "Data models for the file-based knowledge base"
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true

[dev-dependencies]
serde_yaml.workspace = true
