[package]
name = "knowledge-base-validation"
description = "Validation for the file-based knowledge base"
readme = "README.md"
keywords = ["knowledge-base", "yaml", "validation"]
categories = ["development-tools::debugging"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
chrono.workspace = true
knowledge-base-models.workspace = true
knowledge-base-snapshot.workspace = true
language-tags.workspace = true
pulldown-cmark.workspace = true
regex.workspace = true
serde.workspace = true
serde_yaml.workspace = true
url.workspace = true

[dev-dependencies]
tempfile = "3"
